"""migration.

Revision ID: 7fe15e3f847e
Revises: 8d5cde1a048a
Create Date: 2022-05-19 03:15:45.744920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe15e3f847e'
down_revision = '8d5cde1a048a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('topic', sa.String(length=200), nullable=True))
    op.add_column('questions', sa.Column('topic', sa.String(length=200), nullable=True))
    op.add_column('shoutouts', sa.Column('topic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoutouts', 'topic')
    op.drop_column('questions', 'topic')
    op.drop_column('feedback', 'topic')
    # ### end Alembic commands ###
