"""migration

Revision ID: 952d98308cd6
Revises: 
Create Date: 2022-08-08 21:41:12.054744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952d98308cd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
