"""migration.

Revision ID: 9fbaa12ff7ee
Revises: 7fe15e3f847e
Create Date: 2022-05-19 13:16:15.647368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbaa12ff7ee'
down_revision = '7fe15e3f847e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbackcomments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questioncomments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shoutoutcomments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shoutout_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shoutout_id'], ['shoutouts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question-comments')
    op.drop_table('feedback-comments')
    op.drop_table('shoutout-comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoutout-comments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"shoutout-comments_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shoutout_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shoutout_id'], ['shoutouts.id'], name='shoutout-comments_shoutout_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='shoutout-comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shoutout-comments_pkey')
    )
    op.create_table('feedback-comments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"feedback-comments_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name='feedback-comments_feedback_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedback-comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feedback-comments_pkey')
    )
    op.create_table('question-comments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"question-comments_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='question-comments_question_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='question-comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='question-comments_pkey')
    )
    op.drop_table('shoutoutcomments')
    op.drop_table('questioncomments')
    op.drop_table('feedbackcomments')
    # ### end Alembic commands ###
